"$schema" = "./node_modules/wrangler/config-schema.json"
name = "yatdla"
main = "./src/server.js"
# Set this to today's date
compatibility_date = "2026-03-17"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./public/"
binding = "ASSETS"